/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdIndexRouteImport } from './routes/$id.index'
import { Route as IdRawRouteImport } from './routes/$id.raw'
import { Route as IdEditRouteImport } from './routes/$id.edit'
import { Route as IdDownloadRouteImport } from './routes/$id.download'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdIndexRoute = IdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRawRoute = IdRawRouteImport.update({
  id: '/$id/raw',
  path: '/$id/raw',
  getParentRoute: () => rootRouteImport,
} as any)
const IdEditRoute = IdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IdDownloadRoute = IdDownloadRouteImport.update({
  id: '/$id/download',
  path: '/$id/download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$id/download': typeof IdDownloadRoute
  '/$id/edit': typeof IdEditRoute
  '/$id/raw': typeof IdRawRoute
  '/$id/': typeof IdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$id/download': typeof IdDownloadRoute
  '/$id/edit': typeof IdEditRoute
  '/$id/raw': typeof IdRawRoute
  '/$id': typeof IdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$id/download': typeof IdDownloadRoute
  '/$id/edit': typeof IdEditRoute
  '/$id/raw': typeof IdRawRoute
  '/$id/': typeof IdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/$id/download'
    | '/$id/edit'
    | '/$id/raw'
    | '/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/$id/download' | '/$id/edit' | '/$id/raw' | '/$id'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/$id/download'
    | '/$id/edit'
    | '/$id/raw'
    | '/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IdDownloadRoute: typeof IdDownloadRoute
  IdEditRoute: typeof IdEditRoute
  IdRawRoute: typeof IdRawRoute
  IdIndexRoute: typeof IdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/': {
      id: '/$id/'
      path: '/$id'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/raw': {
      id: '/$id/raw'
      path: '/$id/raw'
      fullPath: '/$id/raw'
      preLoaderRoute: typeof IdRawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/edit': {
      id: '/$id/edit'
      path: '/$id/edit'
      fullPath: '/$id/edit'
      preLoaderRoute: typeof IdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/download': {
      id: '/$id/download'
      path: '/$id/download'
      fullPath: '/$id/download'
      preLoaderRoute: typeof IdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IdDownloadRoute: IdDownloadRoute,
  IdEditRoute: IdEditRoute,
  IdRawRoute: IdRawRoute,
  IdIndexRoute: IdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
